services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=catalog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  catalog:
    build:
      context: .
      dockerfile: services/catalog/Dockerfile
    environment:
      - DATABASE_URL=postgresql://app:app@postgres:5432/catalog?schema=public
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  payment:
    build:
      context: .
      dockerfile: services/payment/Dockerfile
    ports:
      - "3002:3002"

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - catalog
      - payment

  web:
    build:
      context: .
      dockerfile: services/web/Dockerfile
    environment:
      - GATEWAY_BASE=http://gateway:8080
    ports:
      - "3000:3000"
    depends_on:
      - gateway

volumes:
  pgdata:
